# http://docs.aws.amazon.com/opsworks/latest/userguide/workingcookbook-attributes-precedence.html

###
# This is the place to override the dependencies cookbook's default attributes.
#
# Do not edit THIS file directly. Instead, create
# "dependencies/attributes/customize.rb" in your cookbook repository and
# put the overrides in YOUR customize.rb file.
###

#normal[:environment_variables][:Thanks] = 'God'
