name        'gethuman'
description 'Installs and configures a Node.js application server & UPDATES ENVIRONMENT VARIABLES'
maintainer  'Get Human'
license     'Apache 2.0'
version     '1.0.0'

depends 'pm2'
depends 'nginx'
depends 'nodejs'
depends 'gethuman'

supports 'amazon'
supports 'centos', '~> 6.0'

provides 'gethuman::ssl'
provides 'gethuman::log'
provides 'gethuman::nginx'
provides 'gethuman::nodejs'
provides 'gethuman::caching'
provides 'gethuman::environment'

recipe 'gethuman::nginx', 'nginx related recipe'
recipe 'gethuman::log', 'Moves logs to CloudWatch'
recipe 'gethuman::nodejs', 'NodeJS process using pm2'
recipe 'gethuman::nginx', 'nginx SSL redirection recipe'
recipe 'gethuman::caching', 'nginx caching / duration recipe'
recipe 'gethuman::environment', 'Set custom environment variaables'
