name        'gethuman'
description 'Installs and configures a Node.js application server & UPDATES ENVIRONMENT VARIABLES'
maintainer  'Get Human'
license     'Apache 2.0'
version     '1.0.0'

depends 'nginx'
depends 'gethuman'

provides 'gethuman::ssl'
provides 'gethuman::log'
provides 'gethuman::nginx'
provides 'gethuman::caching'
provides 'gethuman::nodejs_start'
provides 'gethuman::nodejs_stop'
provides 'gethuman::environment'

recipe 'gethuman::ssl', 'nginx SSL redirection recipe'
recipe 'gethuman::log', 'Moves logs to CloudWatch'
recipe 'gethuman::nginx', 'nginx related recipe'
recipe 'gethuman::caching', 'nginx caching / duration recipe'
recipe 'gethuman::nodejs_start', 'Starts NodeJS process using pm2'
recipe 'gethuman::nodejs_stop', 'Stops NodeJS process using pm2'
recipe 'gethuman::environment', 'Set custom environment variaables'
